// Generated by deps/update_cgo.py.
//go:build cgo && darwin && amd64

package v8go

// #cgo LDFLAGS: -pthread -L${SRCDIR}/deps/darwin_amd64
// #cgo LDFLAGS: -lv8-0 -lv8-1
// #cgo darwin LDFLAGS: -framework CoreFoundation
// #cgo libgcompat LDFLAGS: -lgcompat
// #cgo linux LDFLAGS: -ldl
import "C"
