// Generated by deps/update_cgo.py.
//go:build cgo && android && arm64

package v8go

// Link the native libraries bundled with this checkout directly.

// #cgo LDFLAGS: -pthread -L${SRCDIR}/deps/android_arm64
// #cgo LDFLAGS: -Wl,--start-group -lv8-0 -lv8-1 -lv8-2 -lv8-3 -lc++-cr -lc++abi-cr -Wl,--end-group
// #cgo libgcompat LDFLAGS: -lgcompat
// #cgo linux LDFLAGS: -ldl
import "C"
