// Generated by deps/update_cgo.py.
//go:build cgo && android && amd64

package v8go

// #cgo LDFLAGS: -pthread -L${SRCDIR}/deps/android_amd64
// #cgo LDFLAGS: -Wl,--start-group -lv8-0 -lv8-1 -lv8-2 -Wl,--end-group
// #cgo darwin LDFLAGS: -framework CoreFoundation
// #cgo libgcompat LDFLAGS: -lgcompat
// #cgo linux LDFLAGS: -ldl
import "C"
