// Generated by deps/update_cgo.py.
//go:build cgo && darwin && amd64

package v8go

// Link the native libraries bundled with this checkout directly.

// #cgo LDFLAGS: -pthread -L${SRCDIR}/deps/darwin_amd64
// #cgo LDFLAGS: -lv8-0 -lv8-1 -lv8-2 -lc++-cr -lc++abi-cr -framework CoreFoundation -framework Security
// #cgo libgcompat LDFLAGS: -lgcompat
// #cgo linux LDFLAGS: -ldl
import "C"
